// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDatabaseCluster implements createDatabaseCluster operation.
//
// Create a database cluster on given kubernetes cluster.
//
// POST /kubernetes/{kubernetesName}/database-cluster
func (UnimplementedHandler) CreateDatabaseCluster(ctx context.Context, req *DatabaseCluster, params CreateDatabaseClusterParams) (r CreateDatabaseClusterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatabases implements listDatabases operation.
//
// List of created database clusters on provided kubernetes cluster.
//
// GET /kubernetes/{kubernetesName}/database-cluster
func (UnimplementedHandler) ListDatabases(ctx context.Context, params ListDatabasesParams) (r ListDatabasesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListKubernetesClusters implements listKubernetesClusters operation.
//
// List of registered kubernetes clusters.
//
// GET /kubernetes
func (UnimplementedHandler) ListKubernetesClusters(ctx context.Context) (r ListKubernetesClustersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterKubernetes implements registerKubernetes operation.
//
// Register Kubernetes cluster in the control plane.
//
// POST /kubernetes
func (UnimplementedHandler) RegisterKubernetes(ctx context.Context, req *KubernetesCluster) (r RegisterKubernetesRes, _ error) {
	return r, ht.ErrNotImplemented
}
