// Code generated by ogen, DO NOT EDIT.
package oas

type CreateDatabaseClusterRes interface {
	createDatabaseClusterRes()
}

type ListDatabasesRes interface {
	listDatabasesRes()
}

type ListKubernetesClustersRes interface {
	listKubernetesClustersRes()
}

type RegisterKubernetesRes interface {
	registerKubernetesRes()
}
