// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateDatabaseClusterParams is parameters of createDatabaseCluster operation.
type CreateDatabaseClusterParams struct {
	// Name of kubernetes Cluster.
	KubernetesName string
}

func unpackCreateDatabaseClusterParams(packed middleware.Parameters) (params CreateDatabaseClusterParams) {
	{
		key := middleware.ParameterKey{
			Name: "kubernetesName",
			In:   "path",
		}
		params.KubernetesName = packed[key].(string)
	}
	return params
}

func decodeCreateDatabaseClusterParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateDatabaseClusterParams, _ error) {
	// Decode path: kubernetesName.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kubernetesName",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.KubernetesName = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kubernetesName",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListDatabasesParams is parameters of listDatabases operation.
type ListDatabasesParams struct {
	// Name of kubernetes Cluster.
	KubernetesName string
}

func unpackListDatabasesParams(packed middleware.Parameters) (params ListDatabasesParams) {
	{
		key := middleware.ParameterKey{
			Name: "kubernetesName",
			In:   "path",
		}
		params.KubernetesName = packed[key].(string)
	}
	return params
}

func decodeListDatabasesParams(args [1]string, argsEscaped bool, r *http.Request) (params ListDatabasesParams, _ error) {
	// Decode path: kubernetesName.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kubernetesName",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.KubernetesName = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kubernetesName",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
